filter:
  paths:
    - 'src/*'
  excluded_paths:
    - 'src/**/Tests'
    - 'src/**/Resources'

checks:
  php: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: false

build:
  environment:
    php:
      version: 7.0

  dependencies:
    override:
      - composer install --no-interaction --prefer-source
