services:
#    import.example:
#        class: ImportBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    import_shop.customer_repository:
            class: Doctrine\ORM\EntityRepository
            factory_service: doctrine.orm.default_entity_manager
            factory_method: getRepository
            arguments:
                - "ImportBundle:Shop"

    import.link.parser:
        class: ImportBundle\Services\LinkParser
        arguments: ["@import_shop.customer_repository"]

    import_shopLink.customer_repository:
            class: Doctrine\ORM\EntityRepository
            factory_service: doctrine.orm.default_entity_manager
            factory_method: getRepository
            arguments:
                - "ImportBundle:ProductPageLink"

    import.product.link:
        class: ImportBundle\Services\LinkImporter
        arguments: ["@doctrine.orm.entity_manager", "@import_shopLink.customer_repository"]

    fetch_links.customer_repository:
            class: Doctrine\ORM\EntityRepository
            factory_service: doctrine.orm.default_entity_manager
            factory_method: getRepository
            arguments:
                - "ImportBundle:ProductPageLink"

    import.link.getter:
        class: ImportBundle\Services\LinkGetter
        arguments: ["@fetch_links.customer_repository"]


    import.product.data:
        class: ImportBundle\Services\DataImporter
        arguments: [ @doctrine.orm.entity_manager ]
