process:
    resource: "@ProcessBundle/Controller/"
    type:     annotation
    prefix:   /

import:
    resource: "@ImportBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /


