<?php

namespace ImportBundle\Repository;

/**
 * PriceHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
