<?php

namespace ImportBundle\Repository;

/**
 * ProductPageLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductPageLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
