-- phpMyAdmin SQL Dump
-- version 4.6.0deb1.wily~ppa.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: May 02, 2016 at 01:31 PM
-- Server version: 5.6.30-0ubuntu0.15.10.1
-- PHP Version: 7.0.5-4+donate.sury.org~wily+1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `shops`
--

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

CREATE TABLE `product` (
  `id` int(11) NOT NULL,
  `product_page_link_id` int(11) DEFAULT NULL,
  `shop_id` int(11) NOT NULL,
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `price` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `image` varchar(350) COLLATE utf8_unicode_ci NOT NULL,
  `date_added` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`id`, `product_page_link_id`, `shop_id`, `title`, `price`, `description`, `image`, `date_added`) VALUES
(1, 1, 1, 'Shmutke wind Lycra', '29.95€', 'BUY THIS AWESOME LYCRA.', 'http://www.surfhouse.lt/eshop/image/cache/data/products/gaastra/2016/clip_image003-600x800.jpg', '2016-05-02 13:06:40'),
(2, 2, 1, 'Shmutke one piece onesie green', '79.95€', 'Shmutke WC13 Gray\r\n\r\n100% Cotton. Made in EU. Made for everyday wearing and keeps you warm all the time. Best for all kind of travelling except diving.\r\n \r\n\r\n\r\n\r\nSize  \r\n			Chest  \r\n			Waist  \r\n			Hips  \r\n			Sleeves \r\n			Length \r\n		XS\r\n			100\r\n			94\r\n			110\r\n			64\r\n			150-160\r\n		S\r\n			104\r\n			98\r\n			116\r\n			67\r\n			155-169\r\n		M\r\n			112\r\n			104\r\n			110\r\n			68\r\n			165-180\r\n		L\r\n			120\r\n			108\r\n			116\r\n			68\r\n			180-195\r\n		Xl\r\n			124\r\n			114\r\n			120\r\n			68\r\n			185-195\r\n		XXL\r\n			130\r\n			120\r\n			126\r', 'http://www.surfhouse.lt/eshop/image/cache/data/products/shmutke/shmutke green-600x800.jpeg', '2016-05-02 13:06:49'),
(3, 3, 1, 'Roxy Surf School 5/4/3 Black wetsuit', '159.95€', 'Whole body Wetsuit by Roxy. The Surf School Steamer is a great neoprene suit. Back zip.', 'http://www.surfhouse.lt/eshop/image/cache/data/products/roxy/older/Surf+School+3+2MM+L+SL+Steamer+Wetsuit-600x800.jpg', '2016-05-02 13:06:59'),
(4, 4, 1, 'Roxy Rip Tide Spring wetsuit', '139.95€', 'Sport your girly style while you ride the waves in this floral printed Rip Tide Spring Suit.\r\n\r\nFeatures\r\n\r\nLong sleeve spring suit.\r\n	Contrasting floral printed panels at front and under arms.\r\n	High neckline.\r\n	Back zip design.\r\n	Back zippered pocket for secure storage.\r\n	Thumbholes on sleeves for extra comfort.\r\n \r\n\r\nDetails\r\n\r\n92% Nylon/Polyamide, 8% Elastane Hyperstretch.\r\n	2mm Neoprene.\r\n	UPF 50+ protection.', 'http://www.surfhouse.lt/eshop/image/cache/data/products/roxy/older/arjw403002_riptidespringsuit,v_wbb7_frt1-600x800.jpg', '2016-05-02 13:07:09'),
(5, 5, 1, 'Quiksilver Syncro 3/2mm wetsuit SA302MG BBL BLUE M', '149.95€', 'Features:\r\n\r\n100% Hyperstretch II Neoprene\r\n	Vaporstretch mesh chest panel\r\n	Hydrowrap neck closure\r\n	Flatlock seams\r\n	YKK standard length back zip\r\n	Ectoflex knee pads\r\n	 ', 'http://www.surfhouse.lt/eshop/image/cache/data/products/quiksilver/older/sa402mg_blue_8-600x800.png', '2016-05-02 13:07:19'),
(6, 6, 1, 'Quiksilver Syncro 2/2mm wetsuit SA217MF BKW Black', '149.95€', 'Features:\r\n\r\n100% Hyperstretch II Neoprene\r\n	Vaporstretch mesh chest panel\r\n	Hydrowrap neck closure\r\n	Flatlock seams\r\n	YKK standard length back zip\r\n	Ectoflex knee pads\r\n	 ', 'http://www.surfhouse.lt/eshop/image/cache/data/products/quiksilver/older/sa217mf-600x800.png', '2016-05-02 13:07:31'),
(7, 7, 1, 'Quiksilver Surfschool 5/4/3mm wetsuit SS504MG BKW Black', '159.95€', 'The Cypher has been improved with the addition of Dryoprene, a combo of FN Lite Neoprene and Recycled Poly Infused with CoConut Charcoal making it the warmest, fastest drying thermal lining to date. Combined with Hydrolock Seam Seals, a water-block semi dry zipper and flush lock seals on the wrists and ankles, the Cypher will certainly keep you warm in the line up.\r\n\r\nDetails\r\n\r\nThickness: 5/4/3mm\r\n\r\nNeoprene: FN Lite Neoprene\r\n\r\nSeams: Hydrolock Seam Seals\r\n\r\nZipper: Chest Zip\r\n\r\n \r\n\r\nProduct F', 'http://www.surfhouse.lt/eshop/image/cache/data/products/quiksilver/older/Surf+School+3+2MM+L+SL+Steamer+Wetsuit-600x800.jpg', '2016-05-02 13:07:43'),
(8, 8, 1, 'Quiksilver Outlaw Short Sleeve Rash Vest White', '34.95€', 'Features:\r\n\r\nMens mid neck rash vest\r\n	Raglan sleeves\r\n	6.3oz UV tech Lycra\r\n	Flat lock seams\r\n	Recommended by the Skin Cancer Foundation\r\n	Logo at chest and sleeve\r\n	Material: 92% poly, 8% elastane', 'http://www.surfhouse.lt/eshop/image/cache/data/products/quiksilver/older/quiksilver-rash-vests-quiksilver-outlaw-short-sleeve-rash-vest-white-600x800.jpg', '2016-05-02 13:07:53'),
(9, 9, 1, 'Quiksilver Outlaw Short Sleeve Rash Vest Gray', '34.95€', 'Features:\r\n\r\nMens mid neck rash vest\r\n	Raglan sleeves\r\n	6.3oz UV tech Lycra\r\n	Flat lock seams\r\n	Recommended by the Skin Cancer Foundation\r\n	Logo at chest and sleeve\r\n	Material: 92% poly, 8% elastane', 'http://www.surfhouse.lt/eshop/image/cache/data/products/quiksilver/older/outlaw_sl_grey-600x800.jpg', '2016-05-02 13:08:03'),
(10, 10, 1, 'Quiksilver Outlaw Short Sleeve Rash Vest Blue', '34.95€', 'Features:\r\n\r\nMens mid neck rash vest\r\n	Raglan sleeves\r\n	6.3oz UV tech Lycra\r\n	Flat lock seams\r\n	Recommended by the Skin Cancer Foundation\r\n	Logo at chest and sleeve\r\n	Material: 92% poly, 8% elastane', 'http://www.surfhouse.lt/eshop/image/cache/data/products/quiksilver/older/quiksilver-rash-vests-quiksilver-outlaw-short-sleeve-rash-vest-blue-600x800.jpg', '2016-05-02 13:08:11'),
(11, 11, 1, 'Quiksilver Outlaw Short Sleeve Rash Vest Black', '34.95€', 'Features:\r\n\r\nMens mid neck rash vest\r\n	Raglan sleeves\r\n	6.3oz UV tech Lycra\r\n	Flat lock seams\r\n	Recommended by the Skin Cancer Foundation\r\n	Logo at chest and sleeve\r\n	Material: 92% poly, 8% elastane', 'http://www.surfhouse.lt/eshop/image/cache/data/products/quiksilver/older/quiksilver-rash-vests-quiksilver-outlaw-short-sleeve-rash-vest-black-600x800.jpg', '2016-05-02 13:14:50'),
(12, 12, 1, 'Quiksilver CYPHER hooded 5/4/3mm winter wetsuit', '349.95€', 'Details\r\n\r\nThickness: 5/4/3mm\r\n\r\nNeoprene: FN Lite Neoprene\r\n\r\nSeams: Hydrolock Seam Seals\r\n\r\nZipper: Chest Zip\r\n\r\n \r\n\r\nProduct Features\r\n\r\nHydrolock Seam Seal\r\nThermobamboo\r\nFN Lite Neoprene\r\nFlush Lock Seals on wrists and ankles\r\nWater Block Semi Dry Zip\r\nThermal Smoothie Hood\r\nEcto Flex Knee Pads', 'http://www.surfhouse.lt/eshop/image/cache/data/products/quiksilver/older/q-cypher-654-hdhft-600x800.jpg', '2016-05-02 13:14:59'),
(13, 13, 1, 'Quiksilver CYPHER 5.5/5/4/3mm winter wetsuit', '399.95€', 'The Cypher is geared towards the person who wants an ultra lightweight, flexible and warm wetsuit which will perform in the harshest of winter conditions. The fuseflex system is Quiksilvers solution to do away with stitching. Conventional stitching creates less flexibility within a wetsuit, so the Cypher uses a pressure bonded seal on the seams to add even more flex throughout the wetsuit. To add more warmth to the Cypher, Quiksilver has added their Plio Air Chamber neoprene technology to the ch', 'http://www.surfhouse.lt/eshop/image/cache/data/products/quiksilver/older/Cypher-600x800.jpg', '2016-05-02 13:15:08'),
(14, 14, 1, 'Quiksilver Cypher 3.5mm Hood with Dickie and Hft', '49.95€', 'Quiksilver Cypher 3.5mm Hood will keel you nice and toasty on the coldest days.\r\n\r\nFeatures:\r\n\r\nPlio-tech termal air chamber neoprene\r\n	Bio-fleece thermal lining\r\n	DST (Dual seal treatment)\r\n	GBS (Glued and Blind Sitched)', 'http://www.surfhouse.lt/eshop/image/cache/data/products/quiksilver/older/quiksilver-cypher-full-wetsuit-hood-3.5mm-10590-p-600x800.jpg', '2016-05-02 13:15:20'),
(15, 15, 1, 'Quiksilver Cypher 3.5mm Hood', '44.95€', 'Quiksilver Cypher 3.5mm Hood will keel you nice and toasty on the coldest days.\r\n\r\nFeatures:\r\n\r\nFiber-lite neoprene, super soft and 100% stretch\r\n	Vaporstretch mesh', 'http://www.surfhouse.lt/eshop/image/cache/data/products/quiksilver/older/ech821ms_cypherhooddickie,v_blk_frt1-600x800.jpg', '2016-05-02 13:15:31'),
(16, 16, 1, 'North X-Ride', '599.00€', 'Product\r\n\r\nInformation\r\n\r\nBEST CARVING ABILITIES\r\n	GREAT CONTROL\r\n	MOST COMFORTABLE BOARD\r\nGREAT FOR FLATWATER AND WAVES\r\n	STEP MONO CONCAVE BOTTOM CONCEPT\r\n	BIAX FIBRE CONSTRUCTION\r\nThe X-Ride is one of the most popular boards on the market and is the choise board of riders all over the world. It is designed to be ridden about 3 cm longer than your standard board. The increase in the rocker line helps to make the X-Ride extremely smooth over choppy water. The outline shape is also a little narr', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/xride_16-600x800.png', '2016-05-02 13:15:40'),
(17, 17, 1, 'North Woohoo', '899.00€', 'Product\r\n\r\nInformation\r\n\r\nSMALL TO WELL OVERHEAD HIGH WAVES\r\n	BEST SURFBOARD\r\n	NO INSERTS FOR FOOTSTRAPS\r\nPERFECT IN THE POCKET\r\n	SNAPPY TOP TURNS & TIGHT BOTTOM TURNS\r\n	LIGHT TEAM CONSTRUCTION\r\nThe Pro Surf is aimed at the rider looking for a more traditional shape, yet still wanting maximum performance. By using a straightforward design approach Sky Solbach has created a finely tuned high performance board aimed to suit the power surfing style of some of our top pro riders when the waves are f', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/wohoo_16-600x800.png', '2016-05-02 13:15:48'),
(18, 18, 1, 'North Whip CSC', '899.00€', 'Product\r\n\r\nInformation\r\n\r\nSMALL TO MEDIUM SIZED WAVES & STRAPLESS FREESTYLE\r\n	BEST WAVE FREESTYLE BOARD\r\n	EARLY PLANING\r\nVERY FORGIVING\r\n	FAST BOTTOM TURNS\r\n	CLASSIC CONSTRUCTION\r\nThe Whip CSC is the perfect all round surfboard in the Compact Surf Concept range. It is really easy to ride and very forgiving and the rail design combines with the modern outline to cut through chop effortlessly. On the wave it is great for carving smooth arching turns but it will also allow you to ride it aggressive', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/whip_16-600x800.png', '2016-05-02 13:15:58'),
(19, 19, 1, 'North Wam', '899.00€', 'Product\r\n\r\nInformation\r\n\r\nALL CONDITIONS BEST ALL-ROUND PERFORMANCE\r\n	HIGH PERFORMANCE ALL-ROUNDER\r\n	EASY TO SURF\r\nDRIVY BOTTOM TURNS & EASY TOP TURNS\r\n	GOOD CONTROL\r\n	CLASSIC CONSTRUCTION\r\nThe WAM has been one of our most popular surfboards for many years, but for 2016 it features a brand new shape. The new board combines a wide squash tail with a broader more high performance nose shape. This effectively increases the overall rail line while increasing the surface area of the board. The benefi', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/wam_16-600x800.png', '2016-05-02 13:16:08'),
(20, 20, 1, 'North Wakestyle Bar', '589.00€', ' \r\n\r\nProduct\r\n\r\nInformation\r\n\r\ndeveloped by the Freestyle/Wakestyle Team\r\n	5 lines with low V\r\n	maximum power release delay\r\n	more slack and pop\r\nincludes Hadlow Setup conversion kit\r\n	extra narrow bar width (42 cm)\r\n	single depower line\r\n	bigger chicken loop\r\nThe completely new Wakestyle Bar is based on the Trust Bar but has been fully influenced by the North Kiteboarding Wakestyle/Freestyle Team. They wanted a shorter bar (42cm), a bigger chicken loop, 22m lines, single line depower with a rub', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/Wakestylebar-600x800.png', '2016-05-02 13:16:19'),
(21, 21, 1, 'NORTH VEGAS', '1,159.00€', 'Product\r\n\r\nInformation\r\n\r\nBEST UNHOOKED PERFORMANCE AND POP UNHOOKED\r\n	RESPONSIVE POWER RELEASE DELAY\r\n	WORKS BEST WITH WAKESTYLEBAR\r\n3 RIDING SETUPS WITH NUMEROUS TRIMMING OPTIONS\r\n	DIRECT & FAST TURNING\r\n	LOADED 5TH LINE\r\nThe benchmark was set many years ago by the Vegas, it is the ultimate freestyle weapon used by our Pro Team to have a resounding effect on the world stage. However, it doubles up as a great kite for ambitious riders too, boosting huge airs and providing great rider feedback! ', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/VEGAS-CC3-01-600x800.png', '2016-05-02 13:16:29'),
(22, 22, 1, 'NORTH VEGAS', '1,159.00€', 'Product\r\n\r\nInformation\r\n\r\nBEST UNHOOKED PERFORMANCE AND POP UNHOOKED\r\n	RESPONSIVE POWER RELEASE DELAY\r\n	WORKS BEST WITH WAKESTYLEBAR\r\n3 RIDING SETUPS WITH NUMEROUS TRIMMING OPTIONS\r\n	DIRECT & FAST TURNING\r\n	LOADED 5TH LINE\r\nThe benchmark was set many years ago by the Vegas, it is the ultimate freestyle weapon used by our Pro Team to have a resounding effect on the world stage. However, it doubles up as a great kite for ambitious riders too, boosting huge airs and providing great rider feedback! ', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/VEGAS-HADL-01-600x800.png', '2016-05-02 13:16:40'),
(23, 23, 1, 'NORTH VEGAS', '1,159.00€', 'Product\r\n\r\nInformation\r\n\r\nBEST UNHOOKED PERFORMANCE AND POP UNHOOKED\r\n	RESPONSIVE POWER RELEASE DELAY\r\n	WORKS BEST WITH WAKESTYLEBAR\r\n3 RIDING SETUPS WITH NUMEROUS TRIMMING OPTIONS\r\n	DIRECT & FAST TURNING\r\n	LOADED 5TH LINE\r\nThe benchmark was set many years ago by the Vegas, it is the ultimate freestyle weapon used by our Pro Team to have a resounding effect on the world stage. However, it doubles up as a great kite for ambitious riders too, boosting huge airs and providing great rider feedback! ', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/VEGAS-CC2-011-600x800.jpg', '2016-05-02 13:16:49'),
(24, 24, 1, 'North TS Hadlow', '1,049.00€', 'Product\r\n\r\nInformation\r\n\r\nBEST POP IN THE RANGE\r\n	MASSIVE GRIP\r\n	RIDE WITH OR WITHOUT FINS\r\nPERFORMANCE & COMPETITION ORIENTED\r\n	STEP DOUBLE CONCAVE WITH TRAILERFIN\r\n	PREMIUM PERFORMANCE CONSTRUCTION\r\nThe choice of our freestyle pro riders, the Team Series is the ultimate board for the competitive rider looking for the ultimate in pop! Used by riders like Reno Romeu and Stefan Spiessberger on the world tour the Team Series wears the badge of excellence like no other. The board is exceedingly sti', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/hadlow_16-600x800.png', '2016-05-02 13:17:02'),
(25, 25, 1, 'North TS', '999.00€', 'Product\r\n\r\nInformation\r\n\r\nBEST POP IN THE RANGE\r\n	MASSIVE GRIP\r\n	RIDE WITH OR WITHOUT FINS\r\nPERFORMANCE & COMPETITION ORIENTED\r\n	STEP DOUBLE CONCAVE WITH TRAILERFIN\r\n	PREMIUM PERFORMANCE CONSTRUCTION\r\nThe choice of our freestyle pro riders, the Team Series is the ultimate board for the competitive rider looking for the ultimate in pop! Used by riders like Reno Romeu and Stefan Spiessberger on the world tour the Team Series wears the badge of excellence like no other. The board is exceedingly sti', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/team_series_16-600x800.png', '2016-05-02 13:17:12'),
(26, 26, 1, 'North Spike Textreme', '999.00€', 'Product\r\n\r\nInformation\r\n\r\nULTIMATE LIGHT WIND WEAPON\r\n	EARLIEST PLANING IN THE RANGE\r\n	FANTASTIC UPWIND PERFORMANCE\r\nEXTREMELY LIGHTWEIGHT\r\n	MONO CONCAVE BOTTOM CONCEPT\r\n	TEXTREME CARBON CONSTRUCTION\r\nThe legendary Spike just got better! By taking the test winning shape of the Spike 153 and utilising the most technological advanced constructions techniques available, the ultimate lightwind freeride board has been created! The Textreme carbon construction makes the board about 20 % lighter than t', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/spiketex_16-600x800.png', '2016-05-02 13:17:22'),
(27, 27, 1, 'North Spike', '629.00€', 'Product\r\n\r\nInformation\r\n\r\nLIGHT WIND WEAPON\r\n	SUPER EARLY PLANING\r\n	FANTASTIC UPWIND PERFORMANCE\r\nGREAT FOR FREERIDE\r\n	MONO CONCAVE BOTTOM CONCEPT\r\n	BIAX FIBRE CONSTRUCTION\r\nWhen the wind doesn’t blow the Spike is the board you need to get riding! Available in three sizes for various wind conditions and rider weights there is a Spike to suit everyone. The largest board in the range, the 163 offers the best lowend performance and fantastic upwind ability in the lightest of winds and for the heavi', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/spike_16-600x800.png', '2016-05-02 13:17:33'),
(28, 28, 1, 'North Soleil', '599.00€', 'Product\r\n\r\nInformation\r\n\r\nWOMEN SPECIFIC SHAPE\r\n	PERFECT CONTROL\r\n	VERY FORGIVING SHAPE AND FLEX\r\nSMOOTH RIDE\r\n	STEP MONO CONCAVE BOTTOM CONCEPT\r\n	BIAX FIBRE CONSTRUCTION\r\nThe growth in the number of women taking up kitesurfing is phenomenal and the level of riding is going through the roof. The Soleil blends the perfect shape and flex into an amazing board that is specifically designed for female riders. This board delivers a smooth ride in choppy conditions whilst being very forgiving allowing', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/soleil_16-600x800.png', '2016-05-02 13:17:43'),
(29, 29, 1, 'North Select', '999.00€', 'Product\r\n\r\nInformation\r\n\r\nFASTEST BOARD IN THE RANGE\r\n	EARLY PLANING\r\n	EXTREMELY LIGHTWEIGHT\r\nVERY FORGIVING RIDE\r\n	STEP MONO CONCAVE BOTTOM CONCEPT\r\n	TEXTREME CARBON CONSTRUCTION\r\nThe Select sets the standards for freeride performance, incorporating the most advanced construction techniques and technology with a fast, dynamic shape. It is the lightest, fastest and most responsive kiteboard in the range and is perfect for freeride and freestyle riders looking for the ultimate machine to take the', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/select_16-600x800.png', '2016-05-02 13:17:53'),
(30, 30, 1, 'NORTH REBEL', '1,089.00€', 'Product\r\n\r\nInformation\r\n\r\n·         BIGGEST WINDRANGE\r\n\r\n·         BEST HANGTIME AND HIGHEST JUMPS\r\n\r\n·         BEST SHEET & GO POWER DEVELOPMENT\r\n\r\n·         GREAT UPWIND PERFORMANCE\r\n\r\n·         EASY WATER RELAUNCH\r\n\r\n·         LOADED 5TH LINE\r\n\r\nThe new 2016 Rebel is the ultimate kite for huge jumps and massive hangtime! There have been quite a few changes across the range this year to ensure it still delivers the maximum performance across all the sizes. The smaller sizes in the range now fe', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/REBEL-CC2-01-600x800.png', '2016-05-02 13:18:03'),
(31, 31, 1, 'NORTH REBEL', '1,089.00€', 'Product\r\n\r\nInformation\r\n\r\n·         BIGGEST WINDRANGE\r\n\r\n·         BEST HANGTIME AND HIGHEST JUMPS\r\n\r\n·         BEST SHEET & GO POWER DEVELOPMENT\r\n\r\n·         GREAT UPWIND PERFORMANCE\r\n\r\n·         EASY WATER RELAUNCH\r\n\r\n·         LOADED 5TH LINE\r\n\r\nThe new 2016 Rebel is the ultimate kite for huge jumps and massive hangtime! There have been quite a few changes across the range this year to ensure it still delivers the maximum performance across all the sizes. The smaller sizes in the range now fe', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/REBEL-CC3-01-600x800.png', '2016-05-02 13:18:15'),
(32, 32, 1, 'NORTH REBEL', '1,089.00€', 'Product\r\n\r\nInformation\r\n\r\n·         BIGGEST WINDRANGE\r\n\r\n·         BEST HANGTIME AND HIGHEST JUMPS\r\n\r\n·         BEST SHEET & GO POWER DEVELOPMENT\r\n\r\n·         GREAT UPWIND PERFORMANCE\r\n\r\n·         EASY WATER RELAUNCH\r\n\r\n·         LOADED 5TH LINE\r\n\r\nThe new 2016 Rebel is the ultimate kite for huge jumps and massive hangtime! There have been quite a few changes across the range this year to ensure it still delivers the maximum performance across all the sizes. The smaller sizes in the range now fe', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/REBEL-CC1-01-600x800.png', '2016-05-02 13:18:26'),
(33, 33, 1, 'North Quad Control', '469.00€', ' \r\n\r\nProduct\r\n\r\nInformation\r\n\r\nEVA cushioned winding post with flip-flop function for easy width adjustment\r\n	Vario cleat and sliding stopper for easy height adjustment\r\n	Integrated backline adjuster to trim rear lines\r\n	Fully integrated EVA floater to protect lines and rider\r\n	Exchangeable plastic center part insert\r\nMoulded EVA floater for safety leash prevents line tangling\r\n	Single frontline safety on QuadControl\r\n	Huge depower & absolute safety\r\n	Push pins for Flip-Flop function\r\nThe North ', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/Web_NKB_TrustBar_16-600x800.png', '2016-05-02 13:18:38'),
(34, 34, 1, 'North Pro Surf', '999.00€', 'Product\r\n\r\nInformation\r\n\r\nSMALL TO WELL OVERHEAD HIGH WAVES\r\n	BEST SURFBOARD\r\n	NO INSERTS FOR FOOTSTRAPS\r\nPERFECT IN THE POCKET\r\n	SNAPPY TOP TURNS & TIGHT BOTTOM TURNS\r\n	LIGHT TEAM CONSTRUCTION\r\nThe Pro Surf is aimed at the rider looking for a more traditional shape, yet still wanting maximum performance. By using a straightforward design approach Sky Solbach has created a finely tuned high performance board aimed to suit the power surfing style of some of our top pro riders when the waves are f', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/prosurf_16-600x800.png', '2016-05-02 13:18:48'),
(35, 35, 1, 'North Pro Kontact', '999.00€', 'Product\r\n\r\nInformation\r\n\r\nSMALL TO WELL OVERHEAD HIGH WAVES\r\n	BEST SURFBOARD\r\n	NO INSERTS FOR FOOTSTRAPS\r\nPERFECT IN THE POCKET\r\n	SNAPPY TOP TURNS & TIGHT BOTTOM TURNS\r\n	LIGHT TEAM CONSTRUCTION\r\nThe Pro Surf is aimed at the rider looking for a more traditional shape, yet still wanting maximum performance. By using a straightforward design approach Sky Solbach has created a finely tuned high performance board aimed to suit the power surfing style of some of our top pro riders when the waves are f', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/prokontact_16-600x800.png', '2016-05-02 13:19:00'),
(36, 36, 1, 'North Pro CSC', '999.00€', 'Product\r\n\r\nInformation\r\n\r\nSMALL TO MEDIUM HIGH WAVES & STRAPLESS FREESTYLE\r\n	SNAPPY TOP TURNS & TIGHT BOTTOM TURNS\r\n	GOOD WAVE FREESTYLEBOARD - NO INSERTS\r\nBEST POP FOR AIRS\r\n	GOOD TRAVELING THROUGH THE TURNS\r\n	LIGHT TEAM CONSTRUCTION\r\nThe Pro CSC was a radical change of direction for our famous Pro Series board last year. The 2016 design has been refined even further to keep the board at the very cutting edge of the sport. It excels in small to medium sized waves, offering predictable grip and ', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/procsc_16-600x800.png', '2016-05-02 13:19:10'),
(37, 37, 1, 'North Nugget CSC', '899.00€', 'Product\r\n\r\nInformation\r\n\r\nLIGHTWIND AND SMALL WAVES / MOST FUN IN BAD CONDITIONS\r\n	EARLIEST PLANING BOARD\r\n	TOP UPWIND PERFORMANCE\r\nCONVENIENT SIZE FOR TRAVELLING\r\n	PIVOTS OVER THE TAIL\r\n	CLASSIC CONSTRUCTION\r\nThe Nugget has been a favourite among many riders around the world for a few years now. It excels when the conditions are sub par and makes those not so great days on the water infinitely more fun! For 2016 the board benefits from our Compact Surf Concept, Sky has been working tirelessly o', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/nugget_16-600x800.png', '2016-05-02 13:19:20'),
(38, 38, 1, 'NORTH NEO', '949.00€', ' \r\n\r\nProduct\r\n\r\nInformation\r\n\r\nBEST DRIFTING ABILITY\r\n	RESPONSIVE STEERING WHEN DEPOWERED\r\n	QUICK & CONSISTENT TURNING\r\nVERY POWERFUL (CHOOSE 1-2 KITE SIZES SMALLER)\r\n	EASY WATER RELAUNCH\r\n	MODERATE DELTA 3 STRUT DESIGN\r\nThe Neo is the definition of a high performance wave kite and continues to meet the needs of the rider with ease. Thanks to the design concept behind the Neo and the power it delivers, riders are able to use at least 1-2sqm less in comparison to any other kite. This advantageous', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/NEO-CC1-01-600x800.png', '2016-05-02 13:19:30'),
(39, 39, 1, 'NORTH NEO', '949.00€', ' \r\n\r\nProduct\r\n\r\nInformation\r\n\r\nBEST DRIFTING ABILITY\r\n	RESPONSIVE STEERING WHEN DEPOWERED\r\n	QUICK & CONSISTENT TURNING\r\nVERY POWERFUL (CHOOSE 1-2 KITE SIZES SMALLER)\r\n	EASY WATER RELAUNCH\r\n	MODERATE DELTA 3 STRUT DESIGN\r\nThe Neo is the definition of a high performance wave kite and continues to meet the needs of the rider with ease. Thanks to the design concept behind the Neo and the power it delivers, riders are able to use at least 1-2sqm less in comparison to any other kite. This advantageous', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/NEO-CC2-01-600x800.png', '2016-05-02 13:19:39'),
(40, 40, 1, 'NORTH MONO', '829.00€', 'Product\r\n\r\nInformation\r\n\r\n·         EASY TO USE\r\n\r\n·         EASY FREERIDING ABILITIES\r\n\r\n·         QUICK TURNING SPEED & REACTIVE STEERING\r\n\r\n·         SOFT POWER DEVELOPMENT\r\n\r\n·         GOOD LOWEND & UPWIND PERFORMANCE\r\n\r\n·         ROBUST 1-STRUT DESIGN\r\n\r\nWe are always on the lookout for innovative ways to design and achieve outstanding products, so our team investigated the potential of a lighter kite with fewer struts. Introducing the Mono, the newest family member to the North Kiteboardin', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/MONO-CC11-01-600x800.png', '2016-05-02 13:19:49'),
(41, 41, 1, 'NORTH MONO', '829.00€', 'Product\r\n\r\nInformation\r\n\r\n·         EASY TO USE\r\n\r\n·         EASY FREERIDING ABILITIES\r\n\r\n·         QUICK TURNING SPEED & REACTIVE STEERING\r\n\r\n·         SOFT POWER DEVELOPMENT\r\n\r\n·         GOOD LOWEND & UPWIND PERFORMANCE\r\n\r\n·         ROBUST 1-STRUT DESIGN\r\n\r\nWe are always on the lookout for innovative ways to design and achieve outstanding products, so our team investigated the potential of a lighter kite with fewer struts. Introducing the Mono, the newest family member to the North Kiteboardin', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/MONO-CC12-SEQ-01-600x800.png', '2016-05-02 13:19:59'),
(42, 42, 1, 'NORTH MONO', '829.00€', 'Product\r\n\r\nInformation\r\n\r\n·         EASY TO USE\r\n\r\n·         EASY FREERIDING ABILITIES\r\n\r\n·         QUICK TURNING SPEED & REACTIVE STEERING\r\n\r\n·         SOFT POWER DEVELOPMENT\r\n\r\n·         GOOD LOWEND & UPWIND PERFORMANCE\r\n\r\n·         ROBUST 1-STRUT DESIGN\r\n\r\nWe are always on the lookout for innovative ways to design and achieve outstanding products, so our team investigated the potential of a lighter kite with fewer struts. Introducing the Mono, the newest family member to the North Kiteboardin', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/MONO-CC13-SEQ-01-600x800.png', '2016-05-02 13:20:07'),
(43, 43, 1, 'NORTH MONO', '829.00€', 'Product\r\n\r\nInformation\r\n\r\n·         EASY TO USE\r\n\r\n·         EASY FREERIDING ABILITIES\r\n\r\n·         QUICK TURNING SPEED & REACTIVE STEERING\r\n\r\n·         SOFT POWER DEVELOPMENT\r\n\r\n·         GOOD LOWEND & UPWIND PERFORMANCE\r\n\r\n·         ROBUST 1-STRUT DESIGN\r\n\r\nWe are always on the lookout for innovative ways to design and achieve outstanding products, so our team investigated the potential of a lighter kite with fewer struts. Introducing the Mono, the newest family member to the North Kiteboardin', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/MONO-CC15-SEQ-01-600x800.png', '2016-05-02 13:20:18'),
(44, 44, 1, 'NORTH MONO', '829.00€', 'Product\r\n\r\nInformation\r\n\r\n·         EASY TO USE\r\n\r\n·         EASY FREERIDING ABILITIES\r\n\r\n·         QUICK TURNING SPEED & REACTIVE STEERING\r\n\r\n·         SOFT POWER DEVELOPMENT\r\n\r\n·         GOOD LOWEND & UPWIND PERFORMANCE\r\n\r\n·         ROBUST 1-STRUT DESIGN\r\n\r\nWe are always on the lookout for innovative ways to design and achieve outstanding products, so our team investigated the potential of a lighter kite with fewer struts. Introducing the Mono, the newest family member to the North Kiteboardin', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/MONO-CC16-SEQ-01-600x800.png', '2016-05-02 13:20:30'),
(45, 45, 1, 'NORTH Lizard', '219.00€', ' ', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/Lizard13_508x508_1_1-600x800.jpg', '2016-05-02 13:20:40'),
(46, 46, 1, 'NORTH JUICE', '949.00€', ' \r\n\r\nProduct\r\n\r\nInformation\r\n\r\nPlayful big kite\r\n	Easy handling\r\nEasy, accessible kite\r\n	Amazing agility\r\nThe second generation of our hugely popular light wind freeride kite, the Juice is ideal for those days on the beach when the wind doesn’t arrive. The kite is available in two sizes, 15m and 18m and is designed around a 3-strut platform to ensure it retains a playful nature in the air, despite the large size! The Juice has amazing upwind performance, even in hardly any wind. Unlike some larg', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/Web_NKB_Juice15-600x800.png', '2016-05-02 13:20:52'),
(47, 47, 1, 'North Jaime', '679.00€', 'Product\r\n\r\nInformation\r\n\r\nGREAT POP\r\n	EASY TO RIDE\r\n	MOST VERSATILE BOARD\r\nGOOD COMPROMISE BETWEEN PERFORMANCE & COMFORT\r\n	QUATTRO V BOTTOM CONCEPT\r\n	PREMIUM CONSTRUCTION\r\nThe Jaime has been in the North Kiteboarding range for over 10 years now; it’s a fantastic freeride and freestyle machine that perfectly reflects the way our very own Jaime Herraiz rides. It’s the perfect board for riders who are looking for a great freestyle board without the unforgiving stiffness that some of the top end pro', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/jaime_16-600x800.jpg', '2016-05-02 13:21:01'),
(48, 48, 1, 'North Gonzales', '469.00€', 'Product\r\n\r\nInformation\r\n\r\nEASY TO RIDE\r\n	SMOOTH & COMFORTABLE\r\n	SUPER FORGIVING\r\nGREAT UPWIND PERFORMANCE\r\n	MONO CONCAVE BOTTOM CONCEPT\r\n	BIAX FIBRE CONSTRUCTION\r\nThe Gonzales is one of the easiest to ride kiteboards around. In the smaller sizes it is smooth and forgiving, the larger sizes are perfect for beginners and larger riders. When you are first learning this sport you need a board that will help you to progress and make that progression as fast as possible. The Gonzales does just that wh', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/gonzales_16-600x800.png', '2016-05-02 13:21:12'),
(49, 49, 1, 'North Gambler', '739.00€', 'Product\r\n\r\nInformation\r\n\r\nDESIGNED FOR BOOTS\r\n	LARGE ROCKER\r\n	RIDE WITH OR WITHOUT FINS\r\nSTIFF TO MEDIUM FLEX PATTERN\r\n	STEP DOUBLE CONCAVE SLICK BASE\r\n	BIAX FIBRE CONSTRUCTION\r\nThe Gambler is our park and wakestyle board, ridden by guys like Tom Court and Craig Cunningham as well as Colleen Carroll, the multiple winner of the Triple S event. This is the go-to board for our riders looking to hit the park on the kite or cable. Tough, strong and packed with performance it delivers whatever the con', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/gambler_16-600x800.png', '2016-05-02 13:21:22'),
(50, 50, 1, 'NORTH EVO', '1,159.00€', 'Product\r\n\r\nInformation\r\n\r\nBEST ALL-ROUND KITE IN THE RANGE\r\n	HUGE WIND RANGE\r\n	GREAT HANGTIME & POWERFUL LIFT\r\nGOOD JUMPING ABILITIES\r\n	EXCELLENT UPWIND PERFORMANCE\r\n	HYBRID BETWEEN C-KITE AND DELTA SHAPE\r\nSimply put, the Evo is the all-round maestro from the North Kiteboarding range, guaranteed to get the job done! Any job. We’ve done things different by giving this freeride machine 5 struts instead of 3 struts, because we believe in it. Why? Because with our 5-strut design that has been refine', 'http://www.surfhouse.lt/eshop/image/cache/data/products/North Kiteboarding/EVO-CC1-SEQ-01-600x800.png', '2016-05-02 13:21:31'),
(51, 864, 2, '2013 CrazyFly Sculp 10m2', '500,00€', '2013 CrazyFly Sculp jėgos aitvaras. Pilnas komplektas su pompa, lyšu, baru, kuprine. Būklė labai gera. Šiuo metu yra Vilniaus parduotuvėje.', 'http://www.xpro.lt/471-tm_thickbox_default/2010-cabrinha-switchblade-12m2.jpg', '2016-05-02 13:21:40'),
(52, 865, 2, '2015 Prolimit FX', '139,00€', 'FX trapecija yra gavusi puikų pirkėjų įvertinimą ir pasitikėjimą. Aukšta nugaros atrama ir žema šonų atrama leidžia labai komfortiškai jaustis įprastoje kaitavimo pozicijoje.', 'http://www.xpro.lt/120-tm_thickbox_default/prolimit-fx.jpg', '2016-05-02 13:21:44'),
(53, 866, 2, '2016 Cabrinha  1x with Trimlite', '404,00€', 'Cabrinha komandai pelnytai didžiuojasi savo valdymo sistema, kuri išsiskiria  išbaigtumu, kokybe, saugumu. Nereguliujamo ilgio, maksimaliai išlengvinta. Daugiau informacijos galite rasti gamintojų tinKLAPYje.', 'http://www.xpro.lt/1159-tm_thickbox_default/2016-cabrinha-overdrive1x-with-recoil.jpg', '2016-05-02 13:21:48'),
(54, 867, 2, '2016 Cabrinha Chaos', '1 214,00€', '2015 Pasaulio taurės antros vietos laimėtojas freestyle rungtyje. Jeigu jūs treniruojatės freestyle  triukus tai šis kaitas jums. Greitas, tikslus, puikiai dirba unhook režime. Tik su juo jūs atliksite savo tobulą kiteloopą. Daugiau informacijos apie šį sportišką ir agresyvų aparatą rasite gamintojų tinklapyje. \r\nKaina - aitvaro su kuprine. Valdymo sistema ir pompa parduodami atskirai.', 'http://www.xpro.lt/910-tm_thickbox_default/2015-cabrinha-chaos.jpg', '2016-05-02 13:21:53'),
(55, 868, 2, '2016 Cabrinha Contra', '1 439,00€', 'Šis mažo vėjo aitvaras leis jums  mėgautis kaitavimu kai vėjo greitis tik 3,5-7m/s. \r\n \r\nKaina - aitvaro su kuprine. Valdymo sistema ir pompa parduodami atskirai.\r\n \r\nDaugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/915-tm_thickbox_default/2015-cabrinha-contra.jpg', '2016-05-02 13:21:57'),
(56, 869, 2, '2016 Cabrinha Drifter', '1 124,00€', 'Jau tris metus iš eilės 2012, 2013 ir 2014 su Cabrinha Drifter laimima pasaulio taurė surf rungtyje. Turbūt todėl šis aitvaras tituluojamas kaip geriausias pasaulyje surf kaitas. Jis suprojektuotas bangoms ir bangose atlieka savo darbą idealiai. Akimirksniu reaguoja kai jums reikia aitvaro jėgos ir ramiai leidžia jums mėgautis ir žaisti su  banga sekdamas jus viršuje bei laukdamas komandos. Daugiau informacijos rasite gamintojų tinklapyje.\r\nKaina - aitvaro su kuprine. Valdymo sistema ir pompa pa', 'http://www.xpro.lt/912-tm_thickbox_default/2015-cabrinha-drifter.jpg', '2016-05-02 13:22:02'),
(57, 870, 2, '2016 Cabrinha FX', '1 124,00€', 'Tai naujas Cabrinha kaitas. Jis jums patiks dėl aukštų šuolių, greitumo, tikslumo. Šis aitvaras tai auksinis viduriukas tarp Chaos ir Switchblade modelių.  Daugiau informacijos galite rasti gamintojų tinklapyje. \r\nKaina - aitvaro su kuprine. Valdymo sistema ir pompa parduodami atskirai.\r\n.', 'http://www.xpro.lt/908-tm_thickbox_default/2015-cabrinha-radar.jpg', '2016-05-02 13:22:06'),
(58, 871, 2, '2016 Cabrinha Genesis 2m2', '386,00€', 'Mokomasis  aitvaras, skirtas suprasti ir išmokti valdymą prieš pradedant naudotis didesniais aitvarais.  Kaitas parduodamas be valdymo baro. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/921-tm_thickbox_default/2015-cabrinha-contra.jpg', '2016-05-02 13:22:11'),
(59, 872, 2, '2016 Cabrinha Overdrive1x with recoil', '494,00€', 'Cabrinha komandai pelnytai didžiuojasi savo valdymo sistema, kuri išsiskiria  išbaigtumu, kokybe, saugumu. Reguliuojamo ilgio vairalazdė (baras). Standartinio dydžio ( 48-56cm), XL dydžio (57-65cm). Daugiau informacijos galite rasti gamintojų tinklapyje.', 'http://www.xpro.lt/1150-tm_thickbox_default/2016-cabrinha-overdrive1x-with-recoil.jpg', '2016-05-02 13:22:15'),
(60, 873, 2, '2016 Cabrinha Overdrive1x with Trimlite', '449,00€', 'Cabrinha komandai pelnytai didžiuojasi savo valdymo sistema, kuri išsiskiria  išbaigtumu, kokybe, saugumu. Reguliuojamo ilgio vairalazdė (baras)( 48-56cm). Daugiau informacijos galite rasti gamintojų tinKLAPYje.', 'http://www.xpro.lt/1154-tm_thickbox_default/2016-cabrinha-overdrive1x-with-recoil.jpg', '2016-05-02 13:22:19'),
(61, 874, 2, '2016 Cabrinha Radar', '788,00€', 'Sukurtas maksimaliai greitam jusų kaitavimo įgūdžių progresui. Labai lengvas ir greičiausiai iš vandens kylantis aitvaras. Nepaprastai lengvai ir tiksliai vykdantis jūsų komandas. Daugiau informacijos galite rasti gamintojų tinklapyje. \r\n \r\nKaina - aitvaro su kuprine. Valdymo sistema ir pompa parduodami atskirai.', 'http://www.xpro.lt/901-tm_thickbox_default/2015-cabrinha-radar.jpg', '2016-05-02 13:22:23'),
(62, 875, 2, '2016 Cabrinha Spark 2,6m2', '287,00€', 'Mokomasis  aitvaras, skirtas suprasti ir išmokti valdymą prieš pradedant naudotis didesniais aitvarais.  Daugiau informacijos rasitaldymo baroe gamintojų tinklapyje.', 'http://www.xpro.lt/922-tm_thickbox_default/2015-cabrinha-contra.jpg', '2016-05-02 13:22:29'),
(63, 876, 2, '2016 Cabrinha Switchblade ', '1 034,00€', 'Tai pats populiariausias Cabrinha modelis, kuris jau dešimt metų dominuoja freeride/wakestyle kategorijoje. Pamėgtas kaituotuojų dėl savo geros traukos, stabilumo, tikslumo,  labai plataus  vėjo diapazono, aukštų šuolių, išskirtinio dizaino ir pagaminimo kokybės. Valdyti šį aitvarą ir vienas malonumas.\r\n \r\nKaina - aitvaro su kuprine. Valdymo sistema ir pompa parduodami atskirai.\r\n \r\nDaugiau informacijos galite rasti gamintojų tinklapyje.', 'http://www.xpro.lt/898-tm_thickbox_default/2015-cabrinha-switchblade.jpg', '2016-05-02 13:22:33'),
(64, 877, 2, '2016 Cabrinha Velocity', '1 214,00€', '2012 ir 2013  Pasaulio taurės laimėtojas race disciplinoje. Rimčiausia greičio mašina. Išlengvinta konstrukcija, neįtikėtinai platus vėjo diapazonas,  pati didžiausia galia kiekviename šio aitvaro kvadratiniame metre. Daugiau informacijos galite rasti gamintojų tinklapyje.\r\nKaina - aitvaro su kuprine. Valdymo sistema ir pompa parduodami atskirai.', 'http://www.xpro.lt/919-tm_thickbox_default/2015-cabrinha-velocity.jpg', '2016-05-02 13:22:38'),
(65, 878, 2, '2016 Crazy Fly Sculp', '1 610,00€', 'Viskas ko jums reikia kaitavimui - tai Sculp aitvaras išsiskiriantis savo universalumu. Tinkamas labai plačiam sąlygų ir kaituotojų diapazonui. Dėl savo delta formos jis turi tiesioginį valdymo jausmą, greitai reaguoja į jūsų komandas ir yra stabilus bei tikslus ore. Neįtikėtinas lengvumo jausmas jaučiamas  valdant šį aitvarą.  Aukščiausios kokybės medžiagos iš Vokietijos ir Japonijos naudojamos gaminant šiuos aitvarus. Visa gamyba vykdoma naujutėliame Crazy Fly fabrike. \r\nAitvaras yra pilnai su', 'http://www.xpro.lt/928-tm_thickbox_default/2015-crazy-fly-sculp.jpg', '2016-05-02 13:22:43'),
(66, 879, 2, '2016 CrazyFly  ATV', '659,00€', 'Universaliausia surf lenta CrazyFly asortimente. Su vidutinio dydžio dugno įlinkiu ši lenta anksti išglisuoja ir turi didelį pagreitį. Ją labai lengva kontroliuoti, net ir dideliame greityje. Jeigu jūs ruošiatės treniruotis kaitavimą bangose, tai būtų geriausias pasirinkimas. Daugiau informacijos apie šį žaislą rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1173-tm_thickbox_default/2015-crazyfly-atv.jpg', '2016-05-02 13:22:47'),
(67, 880, 2, '2016 CrazyFly  Classic', '659,00€', 'Suprojektuota kaituoti didelėse, greitose, galingose bangose. Ši lenta turi tvirčiauią konstrukciją, kad išgyventų rūščiose sąlygose. Daugiau informacijos apie šį žaislą rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1175-tm_thickbox_default/2015-crazyfly-atv.jpg', '2016-05-02 13:22:52'),
(68, 881, 2, '2016 CrazyFly  Strapless', '659,00€', 'Sukurta mokintis ir tobulinti naujos kartos freestyle triukus be kojakilpių  bangose. Lengviausia ir daugiausia tūrio turinti lenta ir tai ją padaro tobulą šuoliuse be kilpų. Daugiau informacijos apie šį žaislą rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1174-tm_thickbox_default/2015-crazyfly-atv.jpg', '2016-05-02 13:22:59'),
(69, 882, 2, '2016 CrazyFly Addict', '799,00€', 'Lenta skirta pažengusiems kaituotojams, norintiems praplesti savo galimybių ribas. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1169-tm_thickbox_default/2015-crazyfly-nuke.jpg', '2016-05-02 13:23:04'),
(70, 883, 2, '2016 CrazyFly Allround', '499,00€', 'Puikus kainos kokybės santykis, lengvas ir komfortiškas plaukimas, gražus dizainas. Neįtikėtinai komfortiška minkšta lenta su kuria galima labai aštriai pjautis į vėją. Skirta pradinukams ir vidutinio lygio kaituotuojams. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1167-tm_thickbox_default/2015-crazyfly-allround.jpg', '2016-05-02 13:23:08'),
(71, 884, 2, '2016 CrazyFly Bulldozer', '649,00€', 'Po sėkmingų 2015 metų ir 2016 Bulldozer lenta išlaiko savo stilių  freestyle/wakestyle/crossover ir pagrindines savybes. T.y. keturi išlenkimai išilginėje plokštumoje, konstrukcijoje naudojamas kevlaro pluoštas, unikalios kojakilpės reguliuojamos dvejais diržais, taip pat prie lentos galima prisukti wakeboard apkaustus arba batus ir naudoti ją wakeparke. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1165-tm_thickbox_default/2015-crazyfly-bulldozer.jpg', '2016-05-02 13:23:13'),
(72, 885, 2, '2016 CrazyFly Cruizer ', '699,00€', 'Lengvo vėjo mašina. Sukurta, kad galėtumėte mėgautis kaitavimu pučiant ir nestipriems vėjams. Lengva konstrukcija su panaudotu anglies pluoštu, vidutinis lankstumas, puikios plaukimo savybės. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1170-tm_thickbox_default/2015-crazyfly-cruizer-pro.jpg', '2016-05-02 13:23:18'),
(73, 886, 2, '2016 CrazyFly Cruizer LW', '649,00€', 'Lengvo vėjo mašina. Sukurta, kad galėtumėte mėgautis kaitavimu pučiant ir nestipriems vėjams. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1171-tm_thickbox_default/2015-crazyfly-cruizer-pro.jpg', '2016-05-02 13:23:22'),
(74, 887, 2, '2016 CrazyFly Girls', '649,00€', 'Sukurta ir pagaminta merginoms. Puikiai subalansuotas lentos lankstumas. Lenta skirta vidutinio lygio arba pažengusioms kaituotojoms. Kojakilpės komplektuojamos mažesnio dydžio. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1168-tm_thickbox_default/2015-crazyfly-girls.jpg', '2016-05-02 13:23:26'),
(75, 888, 2, '2016 CrazyFly Raptor', '699,00€', 'Perkamiausia CrazyFly kaitlentė. Šis modelis gaminamas jau dešimtus metus. Medžio šedies ir anglies pluošto derinys su vienu išlenkimu per lentos išilginę ašį suteikia puikias plaukimo savybes. Tai viena universaliausių kaitlenčių, kurios kokybės kainos santykis tiesiog nerealus.  Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1164-tm_thickbox_default/2015-crazyfly-raptor-pro.jpg', '2016-05-02 13:23:30'),
(76, 889, 2, '2016 CrazyFly Raptor  LTD', '819,00€', 'Dvigubas dugno išlenkimas suteikia labai gerą kontrolę posūkiuose, nusileidimuosie po šuolių bei gerą kilimo į vėją kampą. Lenta dėl konstrukcijoje panaudoto anglies pluošto yra labai lengva. Ši lenta tapo labai populiari dėl savo kokybės, panaudojimo  universalumo, puikių charakteristikų ir elegantiškos išvaizdos. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1163-tm_thickbox_default/2015-crazyfly-raptor-pro-ltd.jpg', '2016-05-02 13:23:34'),
(77, 890, 2, '2016 CrazyFly Shox Green', '649,00€', 'Shox Green yra totali užsipjovimo į vėją mašina ir pati komfortiškiausia kaitlentė CrazyFly asortimente. Tuo pačiu tai pati ekologiškiausia lenta, kurios gamyba išsiskiria siekiant aukščiausių ekologijos standartų. Vidutinio standumo, su dvigubu dugno išlenkimu ir specialiai atrinkta mediena ši lenta puikiai absorbuoja vandens nelygumus. Sukurta vidutinio lygio ir pažengusiems kaituotuojams. Daugiau informacijos galite rasti gamintojų tinklapyje.', 'http://www.xpro.lt/1166-tm_thickbox_default/2015-crazyfly-shox-custom.jpg', '2016-05-02 13:23:39'),
(78, 891, 2, '2016 CrazyFly Skim', '349,00€', 'Puikus žaislas lengvam vėjui arba nedidelėms bangoms.  Galima naudoti tiek su kyliukais, tiek be kyliukų. Lenta naudojama be kojakilpių, todėl bus magu atrasti naujas stovėsenas ir naujus triukus. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1172-tm_thickbox_default/2015-crazyfly-skim.jpg', '2016-05-02 13:23:44'),
(79, 892, 2, '2016 NP trapecija BOMB', '186,00€', 'Tobulai subalansuota atramos, komforto ir lengvumo kombinacija . Daugiau informacijos apie jos technines charakteristikas galite rasti gamintojų tinklapyje.\r\nDydis\r\nJuosmuo\r\nKablio dydis\r\nUS\r\n EU\r\nIn\r\nCm\r\nStd\r\nEZ\r\nVyrų\r\n\r\n\r\n\r\n\r\n\r\nXS\r\n46\r\n28-30\r\n71-78\r\n25cm\r\n25cm\r\nS\r\n48\r\n30-32\r\n76-83\r\n25cm\r\n25cm\r\nM\r\n50\r\n32-34\r\n81-88\r\n25cm\r\n25cm\r\nL\r\n52\r\n34-36\r\n86-93\r\n30cm\r\n25cm\r\nXL\r\n54\r\n36-38\r\n91-98\r\n30cm\r\n30cm', 'http://www.xpro.lt/1336-tm_thickbox_default/np-trapecija-3d-kite.jpg', '2016-05-02 13:23:48'),
(80, 893, 2, '2016 NP trapecija BOMB', '186,00€', 'Tobulai subalansuota atramos, komforto ir lengvumo kombinacija . Daugiau informacijos apie jos technines charakteristikas galite rasti gamintojų tinklapyje.\r\nDydis\r\nJuosmuo\r\nKablio dydis\r\nUS\r\n EU\r\nIn\r\nCm\r\nStd\r\nEZ\r\nVyrų\r\n\r\n\r\n\r\n\r\n\r\nXS\r\n46\r\n28-30\r\n71-78\r\n25cm\r\n25cm\r\nS\r\n48\r\n30-32\r\n76-83\r\n25cm\r\n25cm\r\nM\r\n50\r\n32-34\r\n81-88\r\n25cm\r\n25cm\r\nL\r\n52\r\n34-36\r\n86-93\r\n30cm\r\n25cm\r\nXL\r\n54\r\n36-38\r\n91-98\r\n30cm\r\n30cm', 'http://www.xpro.lt/1337-tm_thickbox_default/np-trapecija-3d-kite.jpg', '2016-05-02 13:23:53'),
(81, 894, 2, '2016 NP trapecija BOMB', '186,00€', 'Tobulai subalansuota atramos, komforto ir lengvumo kombinacija . Daugiau informacijos apie jos technines charakteristikas galite rasti gamintojų tinklapyje.\r\nDydis\r\nJuosmuo\r\nKablio dydis\r\nUS\r\n EU\r\nIn\r\nCm\r\nStd\r\nEZ\r\nVyrų\r\n\r\n\r\n\r\n\r\n\r\nXS\r\n46\r\n28-30\r\n71-78\r\n25cm\r\n25cm\r\nS\r\n48\r\n30-32\r\n76-83\r\n25cm\r\n25cm\r\nM\r\n50\r\n32-34\r\n81-88\r\n25cm\r\n25cm\r\nL\r\n52\r\n34-36\r\n86-93\r\n30cm\r\n25cm\r\nXL\r\n54\r\n36-38\r\n91-98\r\n30cm\r\n30cm', 'http://www.xpro.lt/1338-tm_thickbox_default/np-trapecija-3d-kite.jpg', '2016-05-02 13:23:58'),
(82, 895, 2, '2016 NP trapecija Mirage', '180,00€', 'Mažiausiai varžanti judesio laisvę trapecija. Sukurta triukams. Daugiau informacijos apie jos technines charakteristikas galite rasti gamintojų tinklapyje.', 'http://www.xpro.lt/1339-tm_thickbox_default/np-trapecija-3d-kite.jpg', '2016-05-02 13:24:03'),
(83, 896, 2, '2016 NP trapecija Mirage', '180,00€', 'Mažiausiai varžanti judesio laisvę trapecija. Sukurta triukams. Daugiau informacijos apie jos technines charakteristikas galite rasti gamintojų tinklapyje.', 'http://www.xpro.lt/1340-tm_thickbox_default/np-trapecija-3d-kite.jpg', '2016-05-02 13:24:09'),
(84, 897, 2, '2016 NP trapecija Mirage', '180,00€', 'Mažiausiai varžanti judesio laisvę trapecija. Sukurta triukams. Daugiau informacijos apie jos technines charakteristikas galite rasti gamintojų tinklapyje.', 'http://www.xpro.lt/1341-tm_thickbox_default/np-trapecija-3d-kite.jpg', '2016-05-02 13:24:13'),
(85, 898, 2, '2016 NP trapecija Raven', '186,00€', 'Sukurta moterims, įvertinus jų kūno proporcijas.  Daugiau informacijos apie jos technines charakteristikas galite rasti gamintojų tinklapyje.', 'http://www.xpro.lt/1354-tm_thickbox_default/np-trapecija-3d-kite.jpg', '2016-05-02 13:24:18'),
(86, 899, 2, '2016 Prolimit EVO Sport Directional', '64,00€', 'Krepšys vienkryptei lentai. Talpina savyje lentą su kyliukais ir kojakilpėmis. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1195-tm_thickbox_default/prolimit-kitesurf-golf-aero-wheeled.jpg', '2016-05-02 13:24:22'),
(87, 900, 2, '2016 Prolimit EVO Travel Double', '117,00€', 'Pagamintas viekrypčių/wave lentų transportavimui. Vienas skyrius skirtas dviem lentoms, o kitas talpina 2/3 kaitus.   Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1196-tm_thickbox_default/prolimit-kitesurf-golf-aero-wheeled.jpg', '2016-05-02 13:24:26'),
(88, 901, 2, '2016 Prolimit FX', '139,00€', 'FX trapecija yra gavusi puikų pirkėjų įvertinimą ir pasitikėjimą. Aukšta nugaros atrama ir žema šonų atrama leidžia labai komfortiškai jaustis įprastoje kaitavimo pozicijoje. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1189-tm_thickbox_default/prolimit-fx.jpg', '2016-05-02 13:24:31'),
(89, 902, 2, '2016 Prolimit Golf Aero Wheeled', '130,00€', 'Pagamintas iš tvirto 600D poliesterio medžiagos. Su fiksuota ratukų platforma.  Talpina savyke 2-3 jėgos aitvarus ir kaitlentę. Nuimama ratukų bazė.  Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1193-tm_thickbox_default/prolimit-kitesurf-golf-aero-wheeled.jpg', '2016-05-02 13:24:35'),
(90, 903, 2, '2016 Prolimit Golf LTD Wheeled', '150,00€', 'Pagamintas iš tvirto 600D poliesterio medžiagos.  Su fiksuota ratukų platforma.  Talpina savyke 2-3 jėgos aitvarus ir kaitlentę. Integruoti vidiniai diržai suspaudimui. Patogos pakavimas, turi dvi perskirtas erdves.  Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1194-tm_thickbox_default/prolimit-kitesurf-golf-aero-wheeled.jpg', '2016-05-02 13:24:40'),
(91, 904, 2, '2016 Prolimit Kitesurf Golf Ultralight', '70,00€', 'Ypatingai lengvas kelioninis kaitavimo įrangos krepšys. Pagamintas iš tvirto 600D poliesterio medžiagos.   Kompaktiškas, talpina savyke 2-3 jėgos aitvarus ir kaitlentę.  Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1192-tm_thickbox_default/prolimit-kitesurf-golf-aero-wheeled.jpg', '2016-05-02 13:24:45'),
(92, 905, 2, '2016 Prolimit Slider Vest Front Zip', '90,00€', 'Pagaminta iš elastingo neopreno. Apsirengimo patogumui yra šoninis užtrauktukas. Puikiai tinka visiems vandens sportams.   Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1209-tm_thickbox_default/prolimit-liemene-kite-half-padded.jpg', '2016-05-02 13:24:50'),
(93, 906, 2, '2016 Prolimit Sport Twintip', '42,00€', 'Šis maišas skirtas kasdieniam naudojimui. Telpa viena lenta su padukais, kyliukais ir kojakilpėmis. Maišas pasiūtas iš 600D polyester Durable. Maiše įsiūtas nerūdyjančio plieno užtrauktukas.', 'http://www.xpro.lt/1191-tm_thickbox_default/prolimit-bb-sport-tt.jpg', '2016-05-02 13:24:54'),
(94, 907, 2, '2016 Prolimit Stretch Vest Half Padded', '80,00€', 'Liemenė puikiai tinkanti kaitavimui ir buriavimui. Suprojektuota, kad derėtų kombinacijoje su juosmenine trapecija. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1211-tm_thickbox_default/prolimit-liemene-kite-half-padded.jpg', '2016-05-02 13:24:59');
INSERT INTO `product` (`id`, `product_page_link_id`, `shop_id`, `title`, `price`, `description`, `image`, `date_added`) VALUES
(95, 908, 2, '2016 Prolimit Stretch Vest Half Padded', '90,00€', 'Pagaminta iš super elastingo neopreno. Liemenė puikiai tinkanti kaitavimui ir buriavimui. Suprojektuota, kad derėtų kombinacijoje su juosmenine trapecija.\r\n  Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1215-tm_thickbox_default/prolimit-liemene-kite-half-padded.jpg', '2016-05-02 13:25:05'),
(96, 910, 2, 'Aquapac 098', '28,00€', 'Vandens nepraleidžiantis dėklas telefonui. Pagal dydį tinkamas Iphone 1-4 modeliams ar kitiems panašaus dydžio telefonams. Apsaugos jūsų telefoną, net  5m gylyje. Dėklas netrukdo kalbėtis, fotografuoti  ir naudotis visomis kitomis telefono funkcijomis. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/452-tm_thickbox_default/aquapac-348.jpg', '2016-05-02 13:25:09'),
(97, 911, 2, 'Aquapac 108', '28,00€', 'Vandens nepraleidžiantis dėklas telefonui. Pagal dydį tinkamas vidutinio dydžio telefonams, tokiems kaip iPhone 5c, iPhone 5s ar iPhone 6. Apsaugos jūsų telefoną, net  5m gylyje. Dėklas netrukdo kalbėtis, fotografuoti  ir naudotis visomis kitomis telefono funkcijomis. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/592-tm_thickbox_default/aquapac-348.jpg', '2016-05-02 13:25:14'),
(98, 912, 2, 'Aquapac 348', '28,00€', 'Vandens nepraleidžiantis dėklas telefonui. Pagal dydį tinkamas Samsung Galaxy S5 modeliui ar kitiems panašaus dydžio telefonams. Apsaugos jūsų telefoną, net  5m gylyje. Dėklas netrukdo kalbėtis, fotografuoti  ir naudotis visomis kitomis telefono funkcijomis. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/450-tm_thickbox_default/aquapac-348.jpg', '2016-05-02 13:25:18'),
(99, 913, 2, 'Aquapac 350', '69,00€', 'Prie specialaus laikiklio tvirtinamas vandens nepraleidžiantis dėklas telefonui. Galite tvirtinti prie dviračio vairo, šalmo ar kitų norimų vietų. Pagal dydį tinkamas didesniems telefonams, tokiems kaip Samsung Galaxy. Apsaugos jūsų telefoną, net  5m gylyje. Dėklas netrukdo kalbėtis, fotografuoti  ir naudotis visomis kitomis telefono funkcijomis. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/596-tm_thickbox_default/aquapac-348.jpg', '2016-05-02 13:25:22'),
(100, 914, 2, 'Aquapac 358', '35,00€', 'Vandens nepraleidžiantis dėklas telefonui. Pagal dydį tinkamas dideliems telefonams, tokiems kaip iPhone 6 Plus. Apsaugos jūsų telefoną, net  5m gylyje. Dėklas netrukdo kalbėtis, fotografuoti  ir naudotis visomis kitomis telefono funkcijomis. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/599-tm_thickbox_default/aquapac-348.jpg', '2016-05-02 13:25:28'),
(101, 915, 2, 'Aquapac 408', '35,00€', 'Vandens nepraleidžiantis dėklas fotoaparatui. Pagal dydį tinkamas mažiems aparatams. Apsaugos jūsų fotoaparatą, net  5m gylyje.  Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/609-tm_thickbox_default/aquapac-348.jpg', '2016-05-02 13:25:34'),
(102, 916, 2, 'Aquapac 418', '35,00€', 'Vandens nepraleidžiantis dėklas fotoaparatui. Pagal dydį tinkamas mažiems aparatams. Apsaugos jūsų fotoaparatą, net  5m gylyje.  Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/605-tm_thickbox_default/aquapac-348.jpg', '2016-05-02 13:25:39'),
(103, 917, 2, 'Aquapac 448', '40,00€', 'Vandens nepraleidžiantis dėklas fotoaparatui. Pagal dydį tinkamas didesniems aparatams. Apsaugos jūsų fotoaparatą, net  5m gylyje.  Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/603-tm_thickbox_default/aquapac-348.jpg', '2016-05-02 13:25:43'),
(104, 918, 2, 'Cabrinha lyšas PRO', '31,00€', ' Cabrinha PRO saugumo sistemos lyšas.', 'http://www.xpro.lt/464-tm_thickbox_default/cabrinha-lysas.jpg', '2016-05-02 13:25:47'),
(105, 919, 2, 'Cabrinha pompa', '38,00€', 'Cabrinha standartinė kaito pompa.', 'http://www.xpro.lt/465-tm_thickbox_default/cabrinha-pompa.jpg', '2016-05-02 13:25:53'),
(106, 920, 2, 'Cabrinha stropos galinės 24m', '65,00€', 'Standartinės galinės aitvaro stropos. Komplektas: 2vnt  - 24m', 'http://www.xpro.lt/467-tm_thickbox_default/cabrinha-storpos-sonines-24m.jpg', '2016-05-02 13:25:58'),
(107, 921, 2, 'Cabrinha stropos priekinės 16m', '65,00€', 'Standartinės priekinės aitvaro stropos. Komplektas: 2vnt  - 16m', 'http://www.xpro.lt/468-tm_thickbox_default/cabrinha-storpos-sonines-24m.jpg', '2016-05-02 13:26:04'),
(108, 922, 2, 'NP juosta galvai', '16,00€', '2mm neopreno juosta galvos apšiltinimui.', 'http://www.xpro.lt/459-tm_thickbox_default/np-juosta-galvai.jpg', '2016-05-02 13:26:08'),
(109, 923, 2, 'NP liemenė High hook', '119,00€', 'Liemnė buriavimui ir kaitavimui. Suderinta su juosmenine trapecija. Turi šoninį užtrauktuką. Reguliuojasi dydis. Yra kišenė. Labai patvari ir ilgaamžė. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/432-tm_thickbox_default/np-liemene-high-hook.jpg', '2016-05-02 13:26:13'),
(110, 924, 2, 'NP liemenė High hook', '119,00€', 'Liemnė buriavimui ir kaitavimui. Suderinta su juosmenine trapecija. Turi šoninį užtrauktuką. Reguliuojasi dydis. Yra kišenė. Labai patvari ir ilgaamžė. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1326-tm_thickbox_default/np-liemene-high-hook.jpg', '2016-05-02 13:26:18'),
(111, 925, 2, 'NP liemenė Impact Side ZIP', '126,00€', 'Liemenė puikiai tinkanti kaitavimui ir buriavimui. Suprojektuota, kad derėtų kombinacijoje su juosmenine trapecija. Daugiau informacijos rasite gamintojų tinklapyje. ', 'http://www.xpro.lt/435-tm_thickbox_default/np-liemene-impact-side-zip.jpg', '2016-05-02 13:26:23'),
(112, 926, 2, 'NP liemenė Impact Side ZIP', '126,00€', 'Liemenė puikiai tinkanti kaitavimui ir buriavimui. Suprojektuota, kad derėtų kombinacijoje su juosmenine trapecija. Daugiau informacijos rasite gamintojų tinklapyje. ', 'http://www.xpro.lt/1324-tm_thickbox_default/np-liemene-impact-side-zip.jpg', '2016-05-02 13:26:27'),
(113, 927, 2, 'NP neopreninė kepurė', '25,00€', '2mm neopreninė kepurė vandens sportams.', 'http://www.xpro.lt/461-tm_thickbox_default/np-juosta-galvai.jpg', '2016-05-02 13:26:32'),
(114, 928, 2, 'NP neopreninė kepurė', '25,00€', '2mm neopreninė kepurė vandens sportams.', 'http://www.xpro.lt/563-tm_thickbox_default/np-juosta-galvai.jpg', '2016-05-02 13:26:36'),
(115, 929, 2, 'NP neopreninė kepurė', '25,00€', '2mm neopreninė kepurė vandens sportams.', 'http://www.xpro.lt/578-tm_thickbox_default/np-juosta-galvai.jpg', '2016-05-02 13:26:41'),
(116, 930, 2, 'NP neopreninė kepurė', '25,00€', '2mm neopreninė kepurė vandens sportams.', 'http://www.xpro.lt/579-tm_thickbox_default/np-juosta-galvai.jpg', '2016-05-02 13:26:46'),
(117, 931, 2, 'NP šalmas', '70,00€', 'Labai patogus ir lengvas šalmas vandens sportams. Pagamintas iš vandens neįgeriančių medžiagų. Smūgiams atsparus korpusas. Vidinė dalis iš EVA minkštos medžiagos. Reguliuojamas galvos suveržimas. Išimami ausų uždengimai.', 'http://www.xpro.lt/1373-tm_thickbox_default/np-salmas.jpg', '2016-05-02 13:26:51'),
(118, 932, 2, 'NP šalmas PRO Hood', '43,00€', '3mm storio neopreninis šalmas vandens sportams. Pagamintas iš elastingo ir minkšto neopreno. Patogus ir gerai apgaubiantis galvą.', 'http://www.xpro.lt/458-tm_thickbox_default/np-salmas-standard.jpg', '2016-05-02 13:26:56'),
(119, 933, 2, 'NP šalmas Standard', '33,00€', '3mm storio neopreninis šalmas vandens sportams. Pagamintas iš elastingo ir minkšto neopreno. Patogus ir gerai apgaubiantis galvą.', 'http://www.xpro.lt/457-tm_thickbox_default/np-salmas-standard.jpg', '2016-05-02 13:27:00'),
(120, 934, 2, 'NP Surf cap', '32,00€', 'Sukurta buriavimui ir kaitavimui. Turi nuimamą kaklo  apsaugą nuo saulės ir užsegamą fiksuojantį dirželį, kad nepamesti krentant į vandenį. Padaryta iš greitai džiūstančios medžiagos. Lengva ir puikiai besiventiliuojanti.', 'http://www.xpro.lt/795-tm_thickbox_default/np-juosta-galvai.jpg', '2016-05-02 13:27:05'),
(121, 935, 2, 'NP trapecija Flash', '190,00€', 'Pati minkščiausia ir komfortiškiausia trapecija. Daugiau informacijos apie jos technines charakteristikas galite rasti gamintojų tinklapyje.', 'http://www.xpro.lt/368-tm_thickbox_default/np-trapecija-3d-kite.jpg', '2016-05-02 13:27:09'),
(122, 936, 2, 'NP trapecija Mirage', '180,00€', 'Mažiausiai varžanti judesio laisvę trapecija. Sukurta triukams. Daugiau informacijos apie jos technines charakteristikas galite rasti gamintojų tinklapyje.', 'http://www.xpro.lt/364-tm_thickbox_default/np-trapecija-3d-kite.jpg', '2016-05-02 13:27:14'),
(123, 937, 2, 'Skywatch EOLE', '72,00€', 'Tikslus vėjo matuoklis. Jo pagalba matysite momentinį, vidutinį ir maksimalų vėjo greitį. Daugiau informacijos rasite gamintojų tinklapyje. ', 'http://www.xpro.lt/455-tm_thickbox_default/skywatch-explorer-1.jpg', '2016-05-02 13:27:19'),
(124, 938, 2, 'Skywatch Explorer 1', '50,00€', 'Nedidelis, patogus ir tikslus vėjo matuoklis. Jo pagalba matysite momentinį, vidutinį ir maksimalų vėjo greitį. Daugiau informacijos rasite gamintojų tinklapyje. ', 'http://www.xpro.lt/453-tm_thickbox_default/skywatch-explorer-1.jpg', '2016-05-02 13:27:24'),
(125, 939, 2, 'Skywatch Explorer 2', '55,00€', 'Nedidelis, patogus ir tikslus vėjo matuoklis. Jo pagalba matysite momentinį, vidutinį ir maksimalų vėjo greitį ir oro temperatūrą. Daugiau informacijos rasite gamintojų tinklapyje. ', 'http://www.xpro.lt/535-tm_thickbox_default/skywatch-explorer-1.jpg', '2016-05-02 13:27:31'),
(126, 940, 2, 'Skywatch Explorer 3', '78,00€', 'Nedidelis, patogus ir tikslus vėjo bei  temperatūros matuoklis. Yra kompaso funkcija.  Jo pagalba matysite momentinį, vidutinį ir maksimalų vėjo greitį. Daugiau informacijos rasite gamintojų tinklapyje. ', 'http://www.xpro.lt/454-tm_thickbox_default/skywatch-explorer-1.jpg', '2016-05-02 13:27:36'),
(127, 941, 2, 'Skywatch Windoo 1', '67,00€', 'Labai nedidelis, patogus ir tikslus vėjo matuoklis skirtas naudojimui su išmaniuoju telefonu. . Jo pagalba matysite momentinį, vidutinį ir maksimalų vėjo greitį ir oro temperatūrą. Daugiau informacijos rasite gamintojų tinklapyje. ', 'http://www.xpro.lt/536-tm_thickbox_default/skywatch-explorer-1.jpg', '2016-05-02 13:27:41'),
(128, 942, 2, '2012  Fanatic FALCON SLALOM  89L', '700,00€', 'Naudota burlentė. Būklė labai gera. Anglies pluošto konstrukcija.  Šiuo metu yra Vilniaus parduotuvėje.', 'http://www.xpro.lt/479-tm_thickbox_default/2013-jp-x-cite-ride-134l.jpg', '2016-05-02 13:27:46'),
(129, 943, 2, '2012 Fanatic Quad GDS 81L', '926,00€', 'Ši burlentė skirta pažengusiam buriuotojui buriuoti jūroje. Su ja puikiai jausitės bangose. Ypatingai gera kontrolė darant waveridingą.\r\nDouble Glass Sandwich konstrukcija. Lentos tūris - 81L, ilgis - 227cm, plotis - 56,5cm, svoris - 6,3kg, burių diapazonas: 4,0-5,8m2.', 'http://www.xpro.lt/612-tm_thickbox_default/2012-fanatic-quad-gds-81l.jpg', '2016-05-02 13:27:52'),
(130, 944, 2, '2012 Fanatic Ripper HRS 120L', '937,00€', 'Ši vaikiška burlentė puikiai tiks pradinukui ar pažengusiam jaunajam buriuotojui. Su ja lengva mokintis, ji atleidžia klaidas, lengvai sukasi, yra pakankamai stabili ir turi tvirtą stiklo pluošto konstrukciją.  Lentos ilgis - 245cm, plotis - 69cm, tūris - 120L. Lentos viršus padengtas minkštu EVA sluoksniu, kuris apsaugo nuo nusibrozdinimo kritimo ar užlipimo ant lentos metu.  Jinai taip pat gali būti naudojama lengvesnių suaugusiujų kaip puiki freeride burlentė.', 'http://www.xpro.lt/615-tm_thickbox_default/2014-fanatic-shark-hrs-150l.jpg', '2016-05-02 13:27:56'),
(131, 945, 2, '2013 Fanatic Quad TE 75L', '1 420,00€', 'Ši burlentė skirta pažengusiam buriuotojui buriuoti jūroje. Su ja puikiai jausitės bangose. Ypatingai gera kontrolė darant waveridingą.\r\nInnegra Carbon Light Finish konstrukcija. Lentos tūris - 75L, ilgis - 226cm, plotis - 54,5cm, svoris - 6,1kg, burių diapazonas: 3,7-5,3m2.', 'http://www.xpro.lt/613-tm_thickbox_default/2012-fanatic-quad-gds-81l.jpg', '2016-05-02 13:28:01'),
(132, 946, 2, '2013 Fanatic Ray 112L', '955,00€', 'Labai greita burlentė pažengusiam buriuotojui. Skirta dalyvauti burlenčių slalomo varžybose arba tiems kas mėgstą maksimalų greitį. \r\nBiax Glass Sandwich / Light Finish konstrukcija. Lentos tūris - 112L, ilgis - 235cm, plotis - 69cm, svoris - 7,5kg, burių diapazonas: 6,0-8,6m2.', 'http://www.xpro.lt/614-tm_thickbox_default/2013-fanatic-ray-112l.jpg', '2016-05-02 13:28:05'),
(133, 947, 2, '2013 Loftsails Pure lip ', '442,85€', 'Stipriai armuota ir puikiai subalansuota burė skirta buriuoti bangose. ', 'http://www.xpro.lt/722-tm_thickbox_default/2013-loftsails-oxygen-85m2.jpg', '2016-05-02 13:28:11'),
(134, 949, 2, '2014 LOFTsails OXYGEN', '442,00€', 'Labai lengva ir puikiai subalansuota bekemberinė burė. ', 'http://www.xpro.lt/720-tm_thickbox_default/2013-loftsails-oxygen-85m2.jpg', '2016-05-02 13:28:16'),
(135, 950, 2, '2014 Loftsails Racing Blade', '571,50€', 'Profesionali lenktyninė burė slalomo arba maksimalaus greičio rungtims.Su šia bure yra pasiekta  keletas pasaulio greičio rekordų, taip pat laimėtos pergalės ir apdovanojimai pasaulio taurės slalomo varžybose. Burė išsiskiria savo lengvumu ir stabilumu greityje. Keturi kemberiai puikia persiverčia padarius posūkį.  Daugiau informacijos rasite gamintojų tinklapyje. ', 'http://www.xpro.lt/234-tm_thickbox_default/2014-loftsails-racing-blade.jpg', '2016-05-02 13:28:21'),
(136, 951, 2, '2014 Neilpryde Fusion HD 6,7m2', '612,00€', 'Universaliausia Neilpryde burė. Su ja gerai buriuoti įvairiausiomis sąlygomis: gaudyti bangas, aukštai šokinėti, mokintis triukus ar tiesiog freeraidinti. ', 'http://www.xpro.lt/706-tm_thickbox_default/2014-neilpryde-fusion-67m2.jpg', '2016-05-02 13:28:26'),
(137, 952, 2, '2014 RRD FIRERACE W Tech 102L', '699,00€', 'Parduodama idealios būklės (kaip nauja):Kaina su maišu ir kyliuku!Šiuo metu yra Vilniaus XPRO parduotuvėje.', 'http://www.xpro.lt/1016-tm_thickbox_default/2013-jp-x-cite-ride-134l.jpg', '2016-05-02 13:28:32'),
(138, 953, 2, '2015 JP X-Cite Ride Plus ES', '1 100,00€', 'JP Australia X Cite ride Plus jau tapo etalonu burlentės skirtos komfortiškam ir sportiškam buriavimui. 2015 metų modelis net dar labiau sportiškesnis ir greitesnis. Daugiau informacijos apie šią burlentę galite rasti gamintojų tinklapyje.\r\n Su šia burlente lengva buriuoti. Puikus manevringumas ir lengvumo jausmas plaukiant. Burlente išformuota taip, kad turetų didesnį glisavimo paviršių. Tai leidžia labai anksti išglisuoti, o tai pat didesnį stabilumą darant prišvėjinį posukį arba plaukiant len', 'http://www.xpro.lt/97-tm_thickbox_default/2015-jp-x-cite-ride-plus-es.jpg', '2016-05-02 13:28:37'),
(139, 954, 2, '2015 Neilpryde Fusion HD 6.0m2', '588,20€', 'Universaliausia Neilpryde burė. Su ja gerai buriuoti įvairiausiomis sąlygomis: gaudyti bangas, aukštai šokinėti, mokintis triukus ar tiesiog freeraidinti. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/737-tm_thickbox_default/2015-neilpryde-fusion.jpg', '2016-05-02 13:28:43'),
(140, 955, 2, '2015 Neilpryde Hellcat 7.7m2', '670,65€', 'Bekemberinė freeride stiliaus burė turinti lenktyninių burių savybių. Greita ir galinga.  Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/740-tm_thickbox_default/2015-neilpryde-hellcat.jpg', '2016-05-02 13:28:48'),
(141, 956, 2, '2015 Prolimit TYPE T', '121,00€', 'Pati populiariausia ir tarp megėjų ir tarp profesionalių buriuotojų  Prolimit trapecija. Ji visus sužavi savo komfortiškumu. Nerealiai patogi.  Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/782-tm_thickbox_default/prolimit-hybrid.jpg', '2016-05-02 13:28:53'),
(142, 957, 2, '2016  JP Freestyle wave PRO', '2 499,00€', 'Labai universali burlentė mėgstantiems buriuoti įvairiomis sąlygomis. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1426-tm_thickbox_default/2015-jp-x-cite-ride-plus-es.jpg', '2016-05-02 13:28:58'),
(143, 958, 2, '2016  JP Super Lightwind FWS 168L', '2 220,00€', 'Anksčiausiai išglisuojanti burlentė.  Skirta buriuoti pučiant mažiems vėjams. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1435-tm_thickbox_default/2015-jp-x-cite-ride-plus-es.jpg', '2016-05-02 13:29:03'),
(144, 959, 2, '2016  JP Super Lightwind PRO  168L', '2 690,00€', 'Anksčiausiai išglisuojanti burlentė.  Skirta buriuoti pučiant mažiems vėjams. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1434-tm_thickbox_default/2015-jp-x-cite-ride-plus-es.jpg', '2016-05-02 13:29:10'),
(145, 960, 2, '2016 Fanatic Falcon BGS', '1 899,00€', 'Labai greita burlentė pažengusiam buriuotojui. Skirta dalyvauti burlenčių slalomo varžybose arba tiems kas mėgstą maksimalų greitį. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1423-tm_thickbox_default/2013-fanatic-ray-112l.jpg', '2016-05-02 13:29:15'),
(146, 961, 2, '2016 Fanatic Falcon TE', '2 499,00€', 'Profesionali lenktyninė burlentė siekiantiems  maksimalių greičių slalomo distancijoje. Daugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1425-tm_thickbox_default/2013-fanatic-ray-112l.jpg', '2016-05-02 13:29:19'),
(147, 962, 2, '2016 Fanatic Gecko Bamboo', '1 849,00€', 'Labai sėkmingai parduodama burlentė. Nuo pat savo atsiradimo ji pelnė puikius freeride stiliaus buriuotojų  atsiliepimus. Labai lengvai išglisuojanti, stabili, manevringa. Tinkanti tiek pradinukui, tiek pažengusiam buriuotojui. Turi platų burių diapazoną.\r\nDaugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1281-tm_thickbox_default/2012-fanatic-quad-gds-81l.jpg', '2016-05-02 13:29:24'),
(148, 963, 2, '2016 Fanatic Gecko HRS', '1 429,00€', 'Labai sėkmingai parduodama burlentė. Nuo pat savo atsiradimo ji pelnė puikius freeride stiliaus buriuotojų  atsiliepimus. Labai lengvai išglisuojanti, stabili, manevringa. Tinkanti tiek pradinukui, tiek pažengusiam buriuotojui. Turi platų burių diapazoną.\r\nDaugiau informacijos rasite gamintojų tinklapyje.', 'http://www.xpro.lt/1421-tm_thickbox_default/2012-fanatic-quad-gds-81l.jpg', '2016-05-02 13:29:30');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id`),
  ADD KEY `IDX_D34A04ADDA60CB8F` (`product_page_link_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `product`
--
ALTER TABLE `product`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=149;
--
-- Constraints for dumped tables
--

--
-- Constraints for table `product`
--
ALTER TABLE `product`
  ADD CONSTRAINT `FK_D34A04ADDA60CB8F` FOREIGN KEY (`product_page_link_id`) REFERENCES `product_page_link` (`id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
